### ISSUE TITLE
Visual Studio PS4 solution

### ISSUE THREAD

**Issue by cosmy1** [bkaradzic/bx#106]
I see in the toolchain there is no direct support for the PS4 (Orbis) in Visual Studio but just for GMake.

**Comment by bkaradzic** [comment]
There is no support for PS4 at all, that gmake is just stubbed to simplify initial step for those that want to attempt to add support for it.

**Comment by bkaradzic** [comment]
Btw, you should check this commit to figure out how to set up PS4 VS: https://github.com/bkaradzic/GENie/commit/a189d873427660048964c9afd617fe198f0d70a1
