### ISSUE TITLE
Please don't use the gcc internal function names for neon intrinsics

### ISSUE THREAD

**Issue by yshui** [bkaradzic/bx#114]
Those internal functions change after upgrading gcc (e.g. from 4.9 -> 5.2), and breaks compilation.

At the same time there's a stable, standard & well documented way to use those functions:

https://gcc.gnu.org/onlinedocs/gcc-4.6.1/gcc/ARM-NEON-Intrinsics.html

Why not use these?

**Comment by bkaradzic** [comment]
Because they are type safe, and annoying to deal with...

**Comment by yshui** [comment]
I actually converted float4_neon.h to use this interface. MAME compiles fine with it, and seems to work correctly.

**Comment by bkaradzic** [comment]
Can you send PR then?
