### ISSUE TITLE
hashMurmur2A not producing valid hash from input-string on 32-bit systems

### ISSUE THREAD

**Issue by degenerated1123** [bkaradzic/bx#125]
With the latest version of bx, the uniform handling of bgfx breaks. All calls to bgfx::createUniform return a handle of 0 for me.

Reason is the following:
string.h, line 612:

```
inline uint32_t hashMurmur2A(const char* _data)
{
    return hashMurmur2A(StringView(_data) );
}
```

`_data` is set to the name of the uniform here, and hashMurmur2A always returns 0 for me.

The failing part is the `strnlen` you wrote in `StringView::set`:

string.h, line 559:

```
inline size_t strnlen(const char* _str, size_t _max)
    {
        const char* end = _str + _max;
        const char* ptr;
        for (ptr = _str; ptr < end && *ptr != '\0'; ++ptr) {};
        return ptr - _str;
    }
```

As `StringView::set` sets `_max` to `UINT32_MAX`, the `end` pointer will actually overflow on a 32-bit system and end up being smaller than `_str`, which causes the for-loop to immediately exit.

**Comment by bkaradzic** [comment]
Fixed: https://github.com/bkaradzic/bx/commit/a52858520f4dc25135a60d0b7dd52cdf50c50808
