### ISSUE TITLE
using namespace tr1 inside std, breaks compilation.

### ISSUE THREAD

**Issue by pplux** [bkaradzic/bx#128]
This line:
`namespace std { namespace tr1 {}; using namespace tr1;`
at https://github.com/bkaradzic/bx/blob/master/include/bx/bx.h#L85

breaks compilation on Visual Studio 2051, when using regex. The compiler complains about an ambiguous symbol (error C2872). Commenting the line solves the issue. 

Maybe a define to optionally disable the line?

**Comment by bkaradzic** [comment]
Try including this file before regex...

**Comment by pplux** [comment]
```cpp
#include <bx/bx.h>
#include <regex>

void test() {
  std::regex r;
}
```
It doesn't really matter the other, it fails on template expansion inside regex headers:

```
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\regex(2273): error C2872: 'regex_constants': ambiguous symbol
1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\regex(96): note: could be 'std::regex_constants'
1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\regex(5805): note: or       'std::tr1::regex_constants'
```
seems like using `namespace tr1` inside std makes the compiler unable to choose between implementations. Also, note that bx, bgfx, and everything else I've been using compiles just fine with that line commented.
