### ISSUE TITLE
setThreadName bug in iOS/MacOS (thread.cpp)

### ISSUE THREAD

**Issue by septag** [bkaradzic/bx#137]
setThreadName sets the current calling thread name instead of newly created one in iOS/MacOs. 
On those platforms you have to keep the name and call ```pthread_setname_np``` in thread's entry func.

**Comment by bkaradzic** [comment]
If you have fix for it, just submit PR...

**Comment by septag** [comment]
sure. [link](https://github.com/bkaradzic/bx/pull/148)
