### ISSUE TITLE
Building bgfx with SDL2 on Raspberry Pi

### ISSUE THREAD

**Issue by drudru** [bkaradzic/bx#139]
Hi,

I would like to do some full-screen 3D programming on the Raspberry Pi using SDL2 (like retropie). I would also like to use imgui as part of the UI. Given the constraints of the rpi platform and my requirements, I think C++ and bgfx is the best way. You have great documentation and your examples look fantastic.

I tried building bgfx, but I suspected ahead of time that this wouldn't work. The configuration wasn't listed in the 'building' section. If this is too far out of scope for bgfx, I will respect that.

Here is what I did.

I downloaded the latest Raspbian and installed that on a microsd.

I cloned the repos in the build instructions. I then rebuilt genie for linux.
This version of Raspbian (Pixel) already had the gcc toolchain, which was nice.

I then ran:

`../genie/bin/linux/genie --with-examples --with-sdl --gcc=rpi gmake`

then:

`make rpi -j4`

The compiles are failing on X11 includes. I didn't install those libs because I am going to run this as a fullscreen SDL2 app.

What should I change to get further?

**Comment by bkaradzic** [comment]
I haven't ever tested with SDL on RPI. Try just using it as is on RPI.

**Comment by drudru** [comment]
I installed the x11 libs as per the build instructions:

```Shell
sudo apt-get install libgl1-mesa-dev x11proto-core-dev libx11-dev
```

then:

```Shell
sudo apt-get install libgl1-mesa-dev x11proto-core-dev libx11-devmake clean
../genie/bin/linux/genie --with-examples --gcc=rpi gmake
make rpi -j4
```

This fails to link any of the executables. 'undefined reference to symbol 'dlsym@@GLIBC_2.4'.
It looks like '-ldl' is missing as a linker flag.

How is that generated in GENIE?

**Comment by bkaradzic** [comment]
Try adding:
```
		links {
			"rt",
			"dl",
		}
```
in this section: https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L1284

**Comment by drudru** [comment]
That worked. The examples compiled.

I tried running the examples. Most of them work, but there is a problem.
The OpenGL ES rect is displayed in the top left of the framebuffer in a separate overlay. The windowing system is underneath. The window for the OpenGL ES displayis blank (of course), and not aligned. The mouse events are relative to the window vs the OpenGL ES display. Also, the mouse cursor is not shown when over the OpenGL ES display because it belongs to the layer below.

I tried to take a screenshot, but it would only get a screenshot of the windowmanager.

So after searching on the net, it appears as though Open GL ES on the pi is not integrated with X. That is definitely not your responsibility.

Is this expected behaviour? Did it work differently for you when you developed this?

Also, most of the demos return glGetError 0x501. I have not looked into that yet.
Some of the demos do not work at all, but that is to be expected with such limited hardware.

**Comment by bkaradzic** [comment]
> That worked. The examples compiled.

Cool, I'll add that to script.

> Is this expected behaviour? Did it work differently for you when you developed this?

Yeah this is exactly how it works. Anyhow it could be improved, technically I think most of GLES on RPI just stretches over whole screen.

**Comment by bkaradzic** [comment]
Fixed: https://github.com/bkaradzic/bx/commit/954ee9914fa5f3b78b0b29b4ef6645c88b916e4a

**Comment by bkaradzic** [comment]
If you want to poke around see `bcm_host_*` calls in this file: https://github.com/bkaradzic/bgfx/blob/master/src/glcontext_egl.cpp

Improvements for RPi are welcome.

**Comment by drudru** [comment]
Thanks - I will check that out.

**Comment by drudru** [comment]
wow - just realized this was filed against bx - very sorry about that!

**Comment by bkaradzic** [comment]
No worries I didn't pay attention either... :)
