### ISSUE TITLE
Issue with WindowsSDKVersion

### ISSUE THREAD

**Issue by TheJare** [bkaradzic/bx#149]
The Env variable contains the "default" version for the SDK for Visual Studio to use. However, for some reason, it has a backslash at the end at least on my installation. That  backslash ends up in the generated vcxproj files. Apparently MSBuild has no problem with this, but the devenv IDE complains and fails to load the projects.

This fix removes the backslash if present. In toolchain.lua(183), add the line shown below:

	local windowsPlatform = os.getenv("WindowsSDKVersion") or "8.1"
	windowsPlatform = string.gsub(windowsPlatform, "\\", "") -- <---
	if _OPTIONS["with-windows"] then

I suppose a more sophisticated option would be to remove anything that isn't a digit or '.' (devenv seems to complain about not being able to compare the versions as numbers) but without an actual test case I can't recommend it.

**Comment by bkaradzic** [comment]
:+1:
