### ISSUE TITLE
Mac Homebrew formula for bx

### ISSUE THREAD

**Issue by fish2000** [bkaradzic/bx#154]
https://github.com/fish2000/homebrew-praxa/blob/master/bx.rb

… notes and/or PRs are always welcome. Cheers!

**Comment by bkaradzic** [comment]
Cool. I'll mention this in bgfx documentation here: https://bkaradzic.github.io/bgfx/build.html#alternative-build-systems

Do you have formula for bgfx?

**Comment by bkaradzic** [comment]
Also nothing depends on lua -> `depends_on "lua" => :build`, it's all embedded in GENie.

**Comment by fish2000** [comment]
Oh wow ok I will remove the Lua dependency – and also I’ll assuredly cook up a bgfx formula in short order, yes!
