### ISSUE TITLE
musl: even with -DBX_CRT_MUSL forced, CrtFileReader class is not present

### ISSUE THREAD

**Issue by kazblox** [bkaradzic/bx#156]
ex. using the bx library to reference to that function "bx::CrtFileReader reader;" causes gcc to complain that CrtFileReader is not a part of bx, breaking the compile of things that rely on the class, i.e. OSD bgfx interface.

tested with Alpine Linux edge branch, gcc 6.4.0

**Comment by bkaradzic** [comment]
There is no CrtFile* anymore, it got renamed to File*.
