### ISSUE TITLE
Meson build system?

### ISSUE THREAD

**Issue by kerberjg** [bkaradzic/bx#161]
I'd like to add Meson build scripts to `bgfx`, `bx` and `bimg` in order to make them available through Meson's dependency DB (Wrap).

If it's something you'd accept, @bkaradzic, I'd be glad to throw PRs at you :)

Just to give you some background, Meson is a C/C++ focused multiplatform build system slightly similar to Gradle (IMHO).

**Comment by bkaradzic** [comment]
I wouldn't accept it main repository because it would mean I have to maintain it. But I would be glad to mention alternative build system if it's actively maintained in separate repository.

See: https://bkaradzic.github.io/bgfx/build.html#alternative-build-systems

**Comment by kerberjg** [comment]
It's perfectly doable, I'll just email you when it's done for all 3 repos :)
