### ISSUE TITLE
Crtnone.cpp troubles in SDLmame compile

### ISSUE THREAD

**Issue by MacBox360** [bkaradzic/bx#167]
Hello,
I am using a G4 PowerMac with OSX 10.5.8 to compile latest SDLmame release, I have set up the makefile to use GCC 7.2 compiler but when I reach the BX libraries here is what happens:

`Compiling 3rdparty/bx/src/crtnone.cpp...
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'void* strcpy(char*, const char*)':
../../../../../3rdparty/bx/src/crtnone.cpp:50:18: warning: declaration of 'void* strcpy(char*, const char*)' conflicts with built-in declaration 'char* strcpy(char*, const char*)' [-Wbuiltin-declaration-mismatch]
 extern "C" void* strcpy(char* _dst, const char* _src)
                  ^~~~~~
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'void* strncpy(char*, const char*, size_t)':
../../../../../3rdparty/bx/src/crtnone.cpp:56:18: warning: declaration of 'void* strncpy(char*, const char*, size_t)' conflicts with built-in declaration 'char* strncpy(char*, const char*, long unsigned int)' [-Wbuiltin-declaration-mismatch]
 extern "C" void* strncpy(char* _dst, const char* _src, size_t _num)
                  ^~~~~~~
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'const char* strchr(const char*, int)':
../../../../../3rdparty/bx/src/crtnone.cpp:68:24: warning: declaration of 'const char* strchr(const char*, int)' conflicts with built-in declaration 'char* strchr(const char*, int)' [-Wbuiltin-declaration-mismatch]
 extern "C" const char* strchr(const char* _str, int _ch)
                        ^~~~~~
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'const char* strstr(const char*, const char*)':
../../../../../3rdparty/bx/src/crtnone.cpp:83:24: warning: declaration of 'const char* strstr(const char*, const char*)' conflicts with built-in declaration 'char* strstr(const char*, const char*)' [-Wbuiltin-declaration-mismatch]
 extern "C" const char* strstr(const char* _str, const char* _find)
                        ^~~~~~
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'int isprint(int)':
../../../../../3rdparty/bx/src/crtnone.cpp:94:16: error: redefinition of 'int isprint(int)'
 extern "C" int isprint(int _ch)
                ^~~~~~~
In file included from /usr/include/_wctype.h:63:0,
                 from /usr/include/wchar.h:114,
                 from ../../../../../3rdparty/bx/include/bx/string.h:11,
                 from ../../../../../3rdparty/bx/include/bx/error.h:9,
                 from ../../../../../3rdparty/bx/include/bx/readerwriter.h:10,
                 from ../../../../../3rdparty/bx/src/crtnone.cpp:8:
/usr/include/ctype.h:272:1: note: 'int isprint(int)' previously defined here
 isprint(int _c)
 ^~~~~~~
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'int toupper(int)':
../../../../../3rdparty/bx/src/crtnone.cpp:99:16: error: redefinition of 'int toupper(int)'
 extern "C" int toupper (int _ch)
                ^~~~~~~
In file included from /usr/include/_wctype.h:63:0,
                 from /usr/include/wchar.h:114,
                 from ../../../../../3rdparty/bx/include/bx/string.h:11,
                 from ../../../../../3rdparty/bx/include/bx/error.h:9,
                 from ../../../../../3rdparty/bx/include/bx/readerwriter.h:10,
                 from ../../../../../3rdparty/bx/src/crtnone.cpp:8:
/usr/include/ctype.h:315:1: note: 'int toupper(int)' previously defined here
 toupper(int _c)
 ^~~~~~~
../../../../../3rdparty/bx/src/crtnone.cpp: In function 'float powf(float)':
../../../../../3rdparty/bx/src/crtnone.cpp:161:18: warning: declaration of 'float powf(float)' conflicts with built-in declaration 'float powf(float, float)' [-Wbuiltin-declaration-mismatch]
 extern "C" float powf(float _x)
                  ^~~~
../../../../../3rdparty/bx/src/crtnone.cpp:167:19: warning: declaration of 'double pow(double)' conflicts with built-in declaration 'double pow(double, double)' [-Wbuiltin-declaration-mismatch]
 extern "C" double pow(double _x)
                   ^~~
make[2]: *** [../../../../osx_clang/obj/x32/Release/3rdparty/bx/src/crtnone.o] Error 1
make[1]: *** [bx] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [macosx_x86] Error 2`

As partial workaround to let the compile process to go ahead I have manually deleted the "toUpper" and "isPrint" definitions from crtnone.cpp but I don't know how to fix this issue since I am not strictly a programmer. Can this be fixed in some way? Many thanks in advance.

**Comment by bkaradzic** [comment]
You should not be building content of that file if CRT library is detected. Figure out why it's not getting detected properly: https://github.com/bkaradzic/bx/blob/8ee7f1cccb6d6bd37b3bdc63fcf72a3c5c0c21f7/src/crtnone.cpp#L10

Code that detects CRT is located here: https://github.com/bkaradzic/bx/blob/8ee7f1cccb6d6bd37b3bdc63fcf72a3c5c0c21f7/include/bx/platform.h#L222

**Comment by MacBox360** [comment]
Well, for what I can understand I have set up the following variables in platform.h

#define BX_ARCH_32BIT 1
#define BX_COMPILER_GCC             1
#define BX_CPU_ENDIAN_BIG    1
#define BX_CPU_PPC   1
#define BX_CRT_GLIBC  1
#define BX_PLATFORM_OSX        1

All errors on crtnone.cpp are gone but another emerged:


'../../../../../3rdparty/bx/src/thread.cpp: In member function 'void bx::Thread::setThreadName(const char*)':
../../../../../3rdparty/bx/src/thread.cpp:204:3: error: 'pthread_setname_np' was not declared in this scope
   pthread_setname_np(ti->m_handle, _name);
   ^~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bx/src/thread.cpp:204:3: note: suggested alternative: 'pthread_main_np'
   pthread_setname_np(ti->m_handle, _name);
   ^~~~~~~~~~~~~~~~~~
   pthread_main_np
make[2]: *** [../../../../osx_clang/obj/x32/Release/3rdparty/bx/src/thread.o] Error 1
make[1]: *** [bx] Error 2
make[1]: *** Waiting for unfinished jobs....'

**Comment by bkaradzic** [comment]
Well that OSX stuff. I don't really support old OSX versions. So you'll have to backport or comment it out.

Also I never bothered maintaining big endian support after I removed XBOX360 support from it. So you might run into those issues too (esp. if you try to use binary shaders compiled on little endian platform).
