### ISSUE TITLE
Build error on osx

### ISSUE THREAD

**Issue by aceiii** [bkaradzic/bx#168]
Failed to build with the`make osx` command on macOS Sierra 10.12.6 on master branch (451e30b)

I get the following error:
```
make -C .build/projects/gmake-osx config=debug32
==== Building bx (debug32) ====
Creating ../../osx32_clang/obj/x32/Debug/bx/src
allocator.cpp
bx.cpp
commandline.cpp
crtnone.cpp
debug.cpp
dtoa.cpp
easing.cpp
file.cpp
filepath.cpp
hash.cpp
math.cpp
mutex.cpp
os.cpp
../../../src/os.cpp:280:10: fatal error: no member named 'chdir' in the global namespace; did you mean simply 'chdir'?
                return ::chdir(_path);
                       ^~~~~~~
                       chdir
../../../src/os.cpp:270:6: note: 'chdir' declared here
        int chdir(const char* _path)
            ^
1 error generated.
make[2]: *** [../../osx32_clang/obj/x32/Debug/bx/src/os.o] Error 1
make[1]: *** [bx] Error 2
make: *** [osx-debug32] Error 2
```

Originally was trying to build bgfx and got this error, but was able to see that it's coming from the bx library. Thought reverting to an earlier change might help and it did allow me to build bx on it's own, but bgfx failed with other problems due to missing files or other discrepencies.

**Comment by bkaradzic** [comment]
Fixed. https://github.com/bkaradzic/bx/commit/cf9acbfdb09e929b22f698eeb63a48618d6cb3ef
