### ISSUE TITLE
suggestion: UTF-8 only filename api

### ISSUE THREAD

**Issue by cloudwu** [bkaradzic/bx#171]
I saw `dirent_mbstowcs_s` is implement by `mbstowcs_s` or `mbstowcs` now : https://github.com/bkaradzic/bx/blob/master/include/compat/msvc/dirent.h#L751-L759

These api is  dependent on current locale . For a cross platform library, I think using the same one locale like utf-8 would be better (IMO).

We may use `MultiByteToWideChar(CP_UTF8, ...)` directly here  instead of `mbstowcs` .

**Comment by bkaradzic** [comment]
Yes, I'm intending to revisit all string/filepath APIs to make them utf-8 only. Even this dirent is going away once I get native OS support, right now it's just helper to get x-platform code working without too much ifdefery.
