### ISSUE TITLE
invalid reference to stdin/stdout on android

### ISSUE THREAD

**Issue by jimon** [bkaradzic/bx#174]
bgfx/bx builds normally for latest android ndk (16.1 at this time). But generated bx library is unusable because of invalid references to stdin/stdout:

```
  ../../../../bx/src/file.cpp:0: error: undefined reference to 'stdout'
  ../../../../bx/src/file.cpp:0: error: undefined reference to 'stdout'
  ../../../../bx/src/file.cpp:0: error: undefined reference to 'stderr'
```

**Comment by bkaradzic** [comment]
I have no issue building with NDK-r13b.

**Comment by jimon** [comment]
Yes it was fine in older versions, but they removed stdout\stderr in never ones (they still were pointed to /dev/null). For my local fix I replaced `FileWriter` with a no-op one (like you have with `FileReaderImpl`). If you agree it's a good idea - I can make a PR 👍
