### ISSUE TITLE
signed integer overflow

### ISSUE THREAD

**Issue by velkyel** [bkaradzic/bx#176]
https://github.com/bkaradzic/bx/blob/f191b11cf17876d9e2798e8555be42f9b7655eeb/src/semaphore.cpp#L81
when counting BGFX_CONFIG_API_SEMAPHORE_TIMEOUT (5000) then at this place occur signed integer overflow.

**Comment by bkaradzic** [comment]
Try:
```cpp
: dispatch_time(DISPATCH_TIME_NOW, int64_t(_msecs)*1000000)
```

**Comment by bkaradzic** [comment]
Grab latest.
