### ISSUE TITLE
can't be compiled by g++ Ubuntu64

### ISSUE THREAD

**Issue by FlashPanda** [bkaradzic/bx#183]
Hi, since I wanna to compile bx as a shared library, I wrote a CMakeLists.txt file to do it. Here is my file. Pretty simple!
cmake_minimum_required (VERSION 2.8)

project (bx)

include_directories (./include)
include_directories (./3rdparty)

aux_source_directory (./src SRC_DIR)

set (CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")

add_library (bx SHARED ${SRC_DIR})

After use "cmake ." command, and then use "make" command to compile it. I got a problem. The compiler told me that I defined many functions twice in amalgamated.o. I found the file, and opened it. I'm confused. Why do you need to include so many cpp files? when I delete this file, my SHARED library was finished.

I know you must have some reasons to do so, but I can't tell it. So, could you help me ?

**Comment by bkaradzic** [comment]
See how existing build scripts are configured: https://github.com/bkaradzic/bx/blob/master/scripts/bx.lua#L33
