### ISSUE TITLE
Genie uses deprecated _HAS_ITERATOR_DEBUGGING flag in MSVC 14+

### ISSUE THREAD

**Issue by EvanBalster** [bkaradzic/bx#191]
Per my remarks in this thread:  https://github.com/bkaradzic/bgfx/issues/1200

MSVC 2015 [deprecated](https://msdn.microsoft.com/en-us/library/aa985939.aspx) the _HAS_ITERATOR_DEBUGGING macro, and its use makes BGFX's generated Visual Studio projects incompatible with standard ones (for debug builds).  Otherwise the libraries are fully compatible.

The problem can be worked around by disabling this line:  https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L552

I suggest removing this definition, or making it optional in Genie (and off by default).

**Comment by bkaradzic** [comment]
When I used VS2015 I didn't have any problems defining it. Nor I have it now with VS2017.

**Comment by bkaradzic** [comment]
Also you can build bgfx your own script (amalgamated build makes this super easy).

**Comment by EvanBalster** [comment]
The issue isn't with being able to define the macro; it makes BGFX's library files link-time incompatible with standard MSVC ones.  Moreover, iterator debugging works in VS2015+ regardless of whether this macro is defined, making it unnecessary for these targets
