### ISSUE TITLE
Can we use std::xxx instead of float bit hacking?

### ISSUE THREAD

**Issue by TheComet** [bkaradzic/bx#195]
Normally I wouldn't care, but the new constexpr functions in math.inl use a C++14 feature that Visual Studio 14 2015 doesn't support.

Is it really necessary to have custom abs(), IsFinite(), IsNaN(), etc. ? Can I replace those with std::abs(), std::isinf() and std::isnan()?

**Comment by bkaradzic** [comment]
Yes, it's important to have custom one. In your fork you can remove `constexpr` that causes issues with VS2015 compiler (I don't have way of testing it with VS2015 and I dropped support because of that).

**Comment by TheComet** [comment]
I'm more concerned about undefined behaviour. Reading from an inactive field in a union in C++ is undefined, and you can't use reinterpret_cast in a constexpr either. See here:

https://godbolt.org/z/OrFzdi

**Comment by bkaradzic** [comment]
That's not "undefined behaviour", it's just `error: expression is not an integral constant expression`.

**Comment by bkaradzic** [comment]
I removed it from those functions: https://github.com/bkaradzic/bx/commit/ccc1d4d3f88e1ebc3191d295de1cbb8d7fb87e66

**Comment by TheComet** [comment]
The error message is a result of undefined behaviour, because when the result of a constexpr must be constant, the constexpr is evaluated against §4.1 which states:
 ```
A glvalue of a non-function, non-array type T can be converted to a prvalue. If T is an incomplete type, a program that necessitates this conversion is ill-formed. If the object to which the glvalue refers is not an object of type T and is not an object of a type derived from T, or if the object is uninitialized, a program that necessitates this conversion has undeﬁned behavior.
```
(See here for more details on the standard: https://stackoverflow.com/questions/11373203/accessing-inactive-union-member-and-undefined-behavior)

When evaluating a constexpr within a constant context, the compiler is required to check for undefined behavior. And because reading from an inactive field in a union is considered reading an uninitialized value (§9.5 states only one field in a union can be active at any time), this is undefined behaviour. That's why you get that error.

------------

Why not use std::isnan()/std::isinf()? At least those give you defined behavior and they are just as optimizable.

**Comment by bkaradzic** [comment]
> Why not use std::isnan()/std::isinf()?

Because I need bx in project that can't use CRT, nor C++ stdlib.

**Comment by TheComet** [comment]
Ah, well then there's not much you can do about that :/
