### ISSUE TITLE
GCC 8 / C++11

### ISSUE THREAD

**Issue by alekseyt** [bkaradzic/bx#201]
Basically it doesn't build with GCC 8 and `-std=c++11`, i looked into issues and found that similar issue (https://github.com/bkaradzic/bgfx/issues/1567) appeared in VS2015 and indeed `constexpr` was disabled for VS2015, so i did the following change to fix build:

```diff
diff --git a/include/bx/macros.h b/include/bx/macros.h
index 7a9b643..a603141 100644
--- a/include/bx/macros.h
+++ b/include/bx/macros.h
@@ -115,7 +115,7 @@
 
 /// The return value of the function is solely a function of the arguments.
 ///
-#if BX_COMPILER_MSVC && (BX_COMPILER_MSVC <= 1900)
+#if (BX_COMPILER_MSVC && (BX_COMPILER_MSVC <= 1900)) || (BX_COMPILER_GCC && (__cplusplus < 201300))
 #      define BX_CONSTEXPR_FUNC BX_CONST_FUNC
 #else
 #      define BX_CONSTEXPR_FUNC constexpr BX_CONST_FUNC
```

I think `__cplusplus` should work for VS2015 too, but i didn't check so i did this change specifically for GCC, no other changes were required as far as i can see.

Alternatively all those `constexpr` parts could be rewritten to fit C++11 requirements, but it won't be pretty.

I know that Genie build enables `-std=c++14` on bx, but i use homemade CMake scripts for building bx/bimg/bgfx and i don't really feel like switching C++ revision to 14.

Does that fix look good? I can create PR if needed, or how would you recommend to approach this?

**Comment by bkaradzic** [comment]
> Alternatively all those constexpr parts could be rewritten to fit C++11 requirements, but it won't be pretty.

Definitely not.

> CMake scripts for building bx/bimg/bgfx and i don't really feel like switching C++ revision to 14.

Why not? It's 5 years after standard year, so it should be safe. :) https://gist.github.com/bkaradzic/2e39896bc7d8c34e042b#orthodox-c

> Does that fix look good? I can create PR if needed, or how would you recommend to approach this?

It looks good. You can submit it.

**Comment by alekseyt** [comment]
> Why not?

Portability ¯\_(ツ)_/¯ I can compile it with `-std=c++2a` without warnings (alas this won't make it C++20), so there are no major difficulties with bx, constexpr, other features, new C++ revisions and whatsnot, not the top priority though. Also it's a bit unfair that VS2015 users have this liberty but GCC 8 users don't.
