### ISSUE TITLE
Trouble compiling my own library with the bgfx library

### ISSUE THREAD

**Issue by JacomusP** [bkaradzic/bx#206]
Hey I've been trying to compile my own game engine that uses bgfx for rendering and I keep running into this error that it says is coming from the bx library. The errors are shown below. 
![image](https://user-images.githubusercontent.com/8228153/58745414-a6398080-8405-11e9-9173-105ba4324723.png)

Does anybody have any idea what could be causing this? I'm compiling with visual studio 2019. I should note that when I built all of the libraries necessary for bgfx seperately they compiled just fine and the .lib files are included in the project. Also the project that I am trying to build builds a .lib and not a .exe

**Comment by bkaradzic** [comment]
It's probably something with your build options... For Q like these join: https://gitter.im/bkaradzic/bgfx
