### ISSUE TITLE
Out of bounds read in strFind

### ISSUE THREAD

**Issue by timmcd69** [bkaradzic/bx#216]
`template<CharFn fn>`
`inline const char* strFind(const char* _str, int32_t _strMax, const char* _find, int32_t _findMax)`

The strFind template function will cause an out of bounds read on _str if _find is an empty string (_findMax == 0).  A check should be added at the top of the function, something like:
`if (!(_strMax && _findMax)) return NULL;`

**Comment by bkaradzic** [comment]
How did you reproduce this in unit test?

**Comment by timmcd69** [comment]
Found while using Clang's Address Sanitizer.

**Comment by bkaradzic** [comment]
Ok, create unit test that fails due to this error, and then I'll fix it.
