### ISSUE TITLE
strRFindUnsafe starts outside of stringview bounds?

### ISSUE THREAD

**Issue by executionunit** [bkaradzic/bx#218]
```strRFind(StringView("alice"), 'e')```

calls

```strRFindUnsafe(char *, 5, 'e');```

which iterates over 'alice'

```
inline const char* strRFindUnsafe(const char* _str, int32_t _len, char _ch)
{
	for (int32_t ii = _len; 0 <= ii; --ii)
	{
		if (_str[ii] == _ch)
		{
			return &_str[ii];
		}
	}
	return NULL;
}
```

notice how ii is set to 5 and then _str[5] is accessed but that is outside the bounds of the "alice" string which has a valid index range of 0-4 inclusive.

Shouldn't the loop be:

```for (int32_t ii = _len-1; 0 <= ii; --ii)```

**Comment by bkaradzic** [comment]
Yep. Good catch. :+1:
