### ISSUE TITLE
Visual Studio 2019 bx.h #include <alloca.h> file problem

### ISSUE THREAD

**Issue by TomasArce** [bkaradzic/bx#225]
Visual Studio 2019 does not support it. It must be changed to #include <malloc.h>

**Comment by jpcy** [comment]
Add `include/compat/msvc` to your include path, like [this](https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L554).

**Comment by Brouilles** [comment]
Same problem here.
How I can fix the problem @jpcy ? I don't understand. Thanks.

**Comment by TheParadox** [comment]
That include path doesn't work...
If you look at BOTH compats (mingw and msvc): you will notice both have the an alloca.h file.
Lo and behold what is in both: #include <malloc.h>
Suggestion - just get rid of alloca.h and directly include malloc

I spent way to long to come to this realization...
