### ISSUE TITLE
BX_ENABLED() evaluated at run time in debug configuration

### ISSUE THREAD

**Issue by alekseyt** [bkaradzic/bx#236]
I'm having this strange issue with `BX_ENABLED`: i've set `BIMG_DECODE_ASTC=0` at compile time to exclude ASTC from build (per https://github.com/bkaradzic/bimg/pull/37) and this works fine in Release and RelWithDebugInfo configurations, but leads to a link error in Debug configuration:

(GCC 9.2)

```
.../bimg/libbimg.a(image.cpp.o): In function `bimg::imageDecodeToRgba8(bx::AllocatorI*, void*, void const*, unsigned int, unsigned int, unsigned int, bimg::TextureFormat::Enum)':
.../bimg/src/image.cpp:4729: undefined reference to `astc_codec::ASTCDecompressToRGBA(unsigned char const*, unsigned long, unsigned long, unsigned long, astc_codec::FootprintType, unsigned char*, unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
```

I think what happens is that compiler delays `BX_ENABLED()` evaluation to run time if optimization isn't enabled therefore it has to link ASTC libraries.

Below is a short CMake script that can be used to reproduce this, but generally speaking i think the simplest way to fix this is this:

```diff
diff --git a/3rdparty/bx/include/bx/bx.h b/3rdparty/bx/include/bx/bx.h
index 86449a27..acd23db5 100644
--- a/3rdparty/bx/include/bx/bx.h
+++ b/3rdparty/bx/include/bx/bx.h
@@ -23,7 +23,7 @@
 #define BX_IGNORE_C4127(_x) bx::ignoreC4127(!!(_x) )
 
 ///
-#define BX_ENABLED(_x) bx::isEnabled<!!(_x)>()
+#define BX_ENABLED(_x) (!!(_x) )
 
 namespace bx
 {
```

I was able to find this comment:

```c++
/// Template for avoiding MSVC: C4127: conditional expression is constant
template<bool>
constexpr bool isEnabled();
```

But i don't have MSVC. There is also another function:

```c++
inline constexpr bool ignoreC4127(bool _x)
{
	return _x;
}
```

and `BX_IGNORE_C4127()` macro. I assume the intent was to:

```c++
#define BX_ENABLED(_x) (BX_IGNORE_C4127(_x) )
```

But this doesn't evaluate at compile time either. So perhaps it should be:

```c++
#if BX_COMPILER_MSVC
#	define BX_ENABLED(_x) (bx::isEnabled<!!(_x)>() )
#else
#	define BX_ENABLED(_x) (!!(_x) )
#endif // BX_COMPILER_MSVC
```

Am i right? Would you accept a pull request like this from someone without MSVC?

Here is how to reproduce (at least on GCC 9.2):

1. Drop this into `CMakeLists.txt` in `bimg/` directory (this script expects that `bx/` is checked out alongside `bimg/`)

```cmake
set(BIMG_SRC
	src/image.cpp
)

set(BIMG_DECODE_SRC
	src/image_decode.cpp
	src/image_gnf.cpp
)

include_directories(
	../bx/include
	./include
	./3rdparty
	./3rdparty/astc-codec/include
)

add_definitions(
	-DBIMG_DECODE_ASTC=0
)

add_library(bimg STATIC ${BIMG_SRC})
add_library(bimg_decode STATIC ${BIMG_DECODE_SRC})

```

2. `$ mkdir build && cd build`
3. `$ CXX=g++-9 cmake .. -DCMAKE_BUILD_TYPE=Debug` - if default C++ revision in compiler is less than C++14 then additional compile flags might be needed (`-std=c++14`)
4. `make`

Observe compiled `image.cpp.o`:

5. `$ objdump -x CMakeFiles/bimg.dir/src/image.o| grep -i astc`

Output:

```
0000000000000000         *UND*	0000000000000000 _ZN10astc_codec20ASTCDecompressToRGBAEPKhmmmNS_13FootprintTypeEPhmm
000000000000e137 R_X86_64_PC32     _ZN10astc_codec20ASTCDecompressToRGBAEPKhmmmNS_13FootprintTypeEPhmm-0x0000000000000004
```

6. Change build type to Release (or RelWithDebugInfo): `$ CXX=g++-9 cmake .. -DCMAKE_BUILD_TYPE=Release`
7. `make`

Observe compiled `image.cpp.o` again:

8. `$ objdump -x CMakeFiles/bimg.dir/src/image.o| grep -i astc`

In Debug it links to ASTC and then requires binary to also link to ASTC if binary links to `libbimg.a`, in Release this requirement doesn't exist.

Any suggestions?

**Comment by bkaradzic** [comment]
Can you reproduce this issue without changing build system?

**Comment by alekseyt** [comment]
Yes. This is not entirely correct, but it will do for repro:

```diff
diff --git a/scripts/bimg.lua b/scripts/bimg.lua
index 43ea555..9e07774 100644
--- a/scripts/bimg.lua
+++ b/scripts/bimg.lua
@@ -20,6 +20,7 @@ project "bimg"
                path.join(BIMG_DIR, "src/image.*"),
                path.join(BIMG_DIR, "src/image_gnf.cpp"),
 
+               --[[
                path.join(ASTC_CODEC_DIR, "src/decoder/astc_file.*"),
                path.join(ASTC_CODEC_DIR, "src/decoder/codec.*"),
                path.join(ASTC_CODEC_DIR, "src/decoder/endpoint_codec.*"),
@@ -31,11 +32,13 @@ project "bimg"
                path.join(ASTC_CODEC_DIR, "src/decoder/physical_astc_block.*"),
                path.join(ASTC_CODEC_DIR, "src/decoder/quantization.*"),
                path.join(ASTC_CODEC_DIR, "src/decoder/weight_infill.*"),
+               --]]
        }
 
        configuration { "linux-*" }
                buildoptions {
                        "-fPIC",
+                       "-DBIMG_DECODE_ASTC=0",
                }
 
        configuration {}
diff --git a/scripts/bimg_encode.lua b/scripts/bimg_encode.lua
index 46df93c..36347b9 100644
--- a/scripts/bimg_encode.lua
+++ b/scripts/bimg_encode.lua
@@ -30,8 +30,10 @@ project "bimg_encode"
                path.join(BIMG_DIR, "3rdparty/nvtt/**.h"),
                path.join(BIMG_DIR, "3rdparty/pvrtc/**.cpp"),
                path.join(BIMG_DIR, "3rdparty/pvrtc/**.h"),
+               --[[
                path.join(BIMG_DIR, "3rdparty/astc/**.cpp"),
                path.join(BIMG_DIR, "3rdparty/astc/**.h"),
+               --]]
                path.join(BIMG_DIR, "3rdparty/tinyexr/**.h"),
                path.join(BIMG_DIR, "3rdparty/iqa/include/**.h"),
                path.join(BIMG_DIR, "3rdparty/iqa/source/**.c"),
```

1. `make clean`
2. `make linux-release64` (texturec won't link - as expected)
3. `make linux-debug64` (texturec won't link - as expected)

```
$ objdump -x .build/linux64_gcc/obj/x64/Release/bimg/src/image.o | grep -i astc
$ objdump -x .build/linux64_gcc/obj/x64/Debug/bimg/src/image.o | grep -i astc
0000000000000000         *UND*	0000000000000000 _ZN10astc_codec20ASTCDecompressToRGBAEPKhmmmNS_13FootprintTypeEPhmm
000000000000f5b8 R_X86_64_PLT32    _ZN10astc_codec20ASTCDecompressToRGBAEPKhmmmNS_13FootprintTypeEPhmm-0x0000000000000004
```

**Comment by alekseyt** [comment]
I also have this local change in **bx**:

```diff
diff --git a/scripts/toolchain.lua b/scripts/toolchain.lua
index c4a93f2..f16cdd6 100644
--- a/scripts/toolchain.lua
+++ b/scripts/toolchain.lua
@@ -299,6 +299,8 @@ function toolchain(_buildDir, _libDir)
                        location (path.join(_buildDir, "projects", _ACTION .. "-tvos-simulator"))
 
                elseif "linux-gcc" == _OPTIONS["gcc"] then
+                       premake.gcc.cc  = "gcc-7"
+                       premake.gcc.cxx = "g++-7"
                        location (path.join(_buildDir, "projects", _ACTION .. "-linux"))
 
                elseif "linux-gcc-afl" == _OPTIONS["gcc"] then
```

So genie build was done with GCC 7 (7.4.0).

**Comment by bkaradzic** [comment]
Ah I get it, this is actually expected. Linker removes the code, not compiler. It's not possible to link if you don't have symbols, but linker dead code stripping will remove the code.

**Comment by alekseyt** [comment]
I don't think it's a dead code. For example texturec expects ASTC to be linked even with `BIMG_DECODE_ASTC=0`

Here is test program:

```c++
#include "bimg/bimg.h"

int main() {
	bimg::imageDecodeToRgba8(nullptr, nullptr, nullptr, 0, 0, 0, bimg::TextureFormat::RGBA8);
	return 0;
}
```

Release:

```
$ g++-9 -Iinclude test.cpp ./.build/linux64_gcc/bin/libbimgRelease.a ../bx/.build/linux64_gcc/bin/libbxRelease.a -ldl
```

Result: it links.

Debug:

```
$ g++-9 -Iinclude test.cpp ./.build/linux64_gcc/bin/libbimgDebug.a ../bx/.build/linux64_gcc/bin/libbxDebug.a -ldl    
./.build/linux64_gcc/bin/libbimgDebug.a(image.o): In function `bimg::imageDecodeToRgba8(bx::AllocatorI*, void*, void const*, unsigned int, unsigned int, unsigned int, bimg::TextureFormat::Enum)':
/home/alex/projects/bimg/.build/projects/gmake-linux/../../../src/image.cpp:4729: undefined reference to `astc_codec::ASTCDecompressToRGBA(unsigned char const*, unsigned long, unsigned long, unsigned long, astc_codec::FootprintType, unsigned char*, unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
```

Result: link error.

Is that really expected?

**Comment by alekseyt** [comment]
Or do i need to compile astc-codec regardless and then hope that dead code elimination will remove it from object files? I was under impression that `BIMG_DECODE_ASTC` should work at compile time. bkaradzic/bimg#37 says headers still has to be included, i would assume that means that implementation is not?

But if it needs to link astc-codec, then this means that "dead code" wasn't eliminated by linker, isn't it? Why would it need to link dead code to astc-codec libraries? I feel like i'm missing something really obvious, but i'm having hard time grasping what is it.

**Comment by bkaradzic** [comment]
There is no linker when you're creating library, only executable. So if no code references any of those functions they will be removed from executable. You still need all the code inside library to link.

**Comment by alekseyt** [comment]
Hmm. Unfortunately it doesn't. So i've compiled bimg with astc with genie and `BIMG_DECODE_ASTC=0` set in `bimg.lua`.

Release:

```
$ g++-9 -Iinclude test.cpp ./.build/linux64_gcc/bin/libbimgRelease.a ../bx/.build/linux64_gcc/bin/libbxRelease.a -ldl
$ objdump -x ./a.out| grep -i astc | wc -l                                                                           
0
```

ASTC symbols eliminated from binary - works as expected.

Debug:

```
$ g++-9 -Iinclude test.cpp ./.build/linux64_gcc/bin/libbimgDebug.a ../bx/.build/linux64_gcc/bin/libbxDebug.a -ldl    
$ objdump -x ./a.out| grep -i astc | wc -l                                                                       
1518
```

1518 symbols in binary that match "astc".

It seems that it links astc-codec in debug and doesn't link astc-codec in release. It may be argued that dead code isn't eliminated in debug, but in my opinion, dead code should not produce linker errors. I think binary should either link or not link in both configurations at the same time, but not link in one configuration and do not link in another configuration.

I suspect that this is due to `constexpr` being delayed to run time without optimizations enabled, so compiler can't evaluate expression at compile time and eliminate that branch as if it was `if constexpr ()` from C++17. If branch is not eliminated, then it has to link astc-codec because this branch can execute at run time. This doesn't reproduce in release because with optimizations enabled compiler actually evaluates this expression at compile time and eliminates this branch.

Why linker doesn't eliminate this branch is a good question. Perhaps for the same reason: compiler decided that `BX_ENABLED()` (`bx::isEnabled()`) will be evaluated at run time, so linker can't eliminate branch that will be executed at run time.

But i get what you're saying, if compiling and linking astc-codec is the intended way of doing this, then so be it. Please let me know if you need any help with this, i can at least test this on GCC in my custom build of bx/bimg/bgfx. I'm going to close this issue for now. Thank you for looking into this.

**Comment by bkaradzic** [comment]
Try to change in `bx.inl` (`BX_FORCE_INLINE` instead of `inline`):

```
	template<bool>
	BX_FORCE_INLINE constexpr bool isEnabled()
	{
		return true;
	}

	template<>
	BX_FORCE_INLINE constexpr bool isEnabled<false>()
	{
		return false;
	}
```

**Comment by alekseyt** [comment]
No, same effect. I don't think there is entirely legit way to force compiler to evaluate constant expression besides `consteval` (judging by the docs).

This seems to compile in GCC and clang:

```c++
/// Template for avoiding MSVC: C4127: conditional expression is constant
template<bool B>
struct isEnabled
{
	static constexpr bool value = B; // This is stupid
};
```

And `BX_ENABLED()`:

```c++
#define BX_ENABLED(_x) (bx::isEnabled<!!(_x)>::value)
```

I was able to build test app (above) using genie w/o bundling astc with libbimg in both release and debug:

```
$ g++-9 -Iinclude test.cpp ./.build/linux64_gcc/bin/libbimgDebug.a ../bx/.build/linux64_gcc/bin/libbxDebug.a -ldl
$ objdump -x ./a.out| grep -i astc | wc -l                                                                       
0
```

But i don't know if this would work in MSVC or how well this would work overall. It works in my custom build on CMake though.

**Comment by bkaradzic** [comment]
Struct is better:
https://godbolt.org/z/e7K9ch

**Comment by bkaradzic** [comment]
Changed it to struct. :+1: Try it now.

**Comment by alekseyt** [comment]
It works. Thank you very much.
