### ISSUE TITLE
Unable to compile bgfx examples on vs2019 64 bits

### ISSUE THREAD

**Issue by DerickThePoney** [bkaradzic/bx#238]
There's is a casting problem on vs2019 that prevents me from compiling the bgfx samples due to a missing cast in method alignPtr (file allocator.inl, line 33):

inline void* alignPtr(void* _ptr, size_t _extra, size_t _align)

correction is to replace line 33 from 
uintptr_t aligned = bx::alignUp(unaligned, _align);

to 
uintptr_t aligned = bx::alignUp(unaligned, (uint32_t)_align);

I would have submitted a pr, but as I submoduled the whole thing and didn't fork and all it did not work... Sorry for that.

**Comment by bkaradzic** [comment]
I see the issue but don't see it here on VS2019 CI:
https://ci.appveyor.com/project/bkaradzic/bgfx/build/job/d6e7gj658rgo3o6n

Do you have some other settings?

**Comment by DerickThePoney** [comment]
Not that I know of. The SDK version i use is 10.0.18362.0 (I had to upgrade this on each project as the default generated by genie is sdk 8.1), and I have v142 of visual studio. Other than that no.

**Comment by bkaradzic** [comment]
Yeah, just checked, and probably CI uses older compiler... Will fix this later today.

**Comment by DerickThePoney** [comment]
That is perfect thanks !
