### ISSUE TITLE
crt0.h not found on alpine linux (MUSL)

### ISSUE THREAD

**Issue by coderofsalvation** [bkaradzic/bx#242]
First of all thanks for the great work!

I tried compiling on alpine linux (MUSL), and got a long way until this:

```
crtnone.cpp
../../../../bx/src/crtnone.cpp:15:10: fatal error: crt0.h: No such file or directory
 #include "crt0.h"
          ^~~~~~~~
```

I tried: adding ` -DEX_CRT_MUSL=1` to `build/projects/gmake-linux/bx.make` (of two-repo)

> any advice?

**Comment by bkaradzic** [comment]
`BX_CRT_MUSL=1` not `EX_CRT_MUSL=1`

**Comment by bkaradzic** [comment]
MUSL does not have way to get identified so you have to add that define:

From:
https://www.openwall.com/lists/musl/2013/02/08/9

> This kind of macro intentionally isn't provided, because its presence
> would result in the vast majority of projects treating bug reports of
> the form "your program does not compile against musl" with a quick
> hack adding "#ifdef __MUSL__ ... [omit feature or substitute in
> fallback definition] ... #endif". In a best case, this would harm
> functionality by leaving the feature out even in later musl versions
> that support it; in reality, it's likely to actively break build (e.g.
> with conflicting declarations/macros/etc.) if the feature is added to
> musl.

Justification is idiotic because it doesn't consider cross-platform projects that need to work with many different CRT/libc libraries.
