### ISSUE TITLE
Possible problem with min() and max()

### ISSUE THREAD

**Issue by hwd71** [bkaradzic/bx#252]
Hi
On win32, these exist already. I can work around it with undef in bx.h, e.g.

```
#if BX_COMPILER_MSVC
#	define BX_IGNORE_C4127(_x) bx::ignoreC4127(!!(_x) )
#   undef max
#   undef min
#else
#	define BX_IGNORE_C4127(_x) (!!(_x) )
#endif // BX_COMPILER_MSVC
```

But then building with another library that expects the other min/max is problematic, e.g. CLI11. 

Thanks
PS: loving GENie.

**Comment by bkaradzic** [comment]
Do this instead:

```
#define NOMINMAX
#include <windows.h>
```

Or pass `NOMINMAX` define via compiler options.

**Comment by hwd71** [comment]
Lovely, thanks!
