### ISSUE TITLE
MAME embedded bx missing crt0.h, suspect MacOSX configuration problem

### ISSUE THREAD

**Issue by atalkingegg** [bkaradzic/bx#263]
Hello,

MAME builds have been broken under MacOSX for a while (V. 0218), I thought I'd look into why. The default build on Mac errors out in the bx 3rd party code section with...
bx/src/crtnone.cpp:15:10: fatal error: crt0.h: No such file or directory  
15 | #include "crt0.h

Looking at the code's source here on github, it's also referencing this non-existing file.
Dropping in an empty crt0.h ends up triggering an entire collection of function type miss-matches, but probably not coming from functions that should be enabled.

I see there's a "BX_PLATFORM_OSX", but defining it in the build files causes a new set of problems. It doesn't look like switching it to a value 1 in platform.h doesn't seem to change anything.

What is the proper way to get bx / bgfx configured and building under MacOSX using XCode clang, or GNU-GCC g++?

Thanks!

**Comment by bkaradzic** [comment]
Do not define `BX_CRT_NONE` and it will compile.
