### ISSUE TITLE
Filepath getExt() returns incorrect extensions.

### ISSUE THREAD

**Issue by JannesN** [bkaradzic/bx#265]
GetExt searches for the file extension using a strFind instead of a strRFind. This causes incorrect results for paths containing more than one dot.

E.g. bx::FilePath("C:\\My.Folder\Test.png").getExt() returns ".Folder\Test.png"

StringView FilePath::getExt() const
	{
		const StringView fileName = getFileName();
		if (!fileName.isEmpty() )
		{
			const StringView dot = **strFind(fileName, '.');** //Incorrect right here!
			return StringView(dot.getPtr(), fileName.getTerm() );
		}

		return StringView();
	}

**Comment by bkaradzic** [comment]
It does work correctly:

Add this:

```
	{ "C:\\My.Folder\\Test.png", true, "C:/My.Folder/", "Test.png", "Test", ".png" },
```

here: https://github.com/bkaradzic/bx/blob/51f25ba638b9cb35eb2ac078f842a4bed0746d56/tests/filepath_test.cpp#L89

to verify it.

Also extension is complete suffix in this case, and I'll update docs to clarify it.

**Comment by JannesN** [comment]
Oh true! My example was just bad. So it is complete suffix of the file name. That explains the issue we were seeing.

**Comment by bkaradzic** [comment]
I see how this can be obnoxious if someone uses dots as separators, but that should be fixed instead. :)
