### ISSUE TITLE
[typetraits.inl] msvc __is_aggregate error

### ISSUE THREAD

**Issue by Crydsch** [bkaradzic/bx#285]
I noticed a little compiler issue with msvc and the `__is_aggregate` function.
For some reason it generates a [C2760 Error](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2760?view=msvc-170)
`syntax error: '__is_aggregate' was unexpected here; expected 'expression'   typetraits.inl   165`

I am not sure what happens here, maybe not supported, may be a compiler bug.
Anyway, I am not using any typetraits, but since it is included by bx.h the compiler complains.

For now I fixed it by removing the entire function.
I am using VS2022 with C++20. I you need any other information please let me know.

**Comment by Crydsch** [comment]
A little testing reveals a simple fix: 
```
template<typename Ty>
inline constexpr bool isAggregate()
{
	return !!__is_aggregate(Ty);
}
```

Not sure why, but that seems to fix it. I guess it is bug after all.

A few quick tests confirm that the function can detect aggregate types correctly.
That being said, I am not very well versed with this typetrait stuff..

**Comment by bkaradzic** [comment]
> I noticed a little compiler issue with msvc and the __is_aggregate function.

You get this compiler error without instantiating template?

**Comment by bkaradzic** [comment]
Can you reproduce the issue on compiler explorer?
https://godbolt.org/z/986fraTdj

I just tried it and not getting any issue with different versions of MSVC compiler.

**Comment by Crydsch** [comment]
So i can reproduce it from msvc v19.30 onwards (i am on latest).
Interestingly only with C++20 enabled.
https://godbolt.org/z/KWYh9888W

Perhaps it got deprecated?

Also, Instantiation is not necessary just code generation in general.
Apparently the compiler will generate template functions, even if not in use...

**Comment by bkaradzic** [comment]
Yeah, your fix with `!!` is fine, no need to change, I just want to understand the issue, and then do fix.
I also noticed `__is_aggregate` changes behavior depending on C++ standard set. For example I tested between 14 vs 17.

**Comment by Crydsch** [comment]
Works like charm now. Thanks :)
