### ISSUE TITLE
pthread_np.h does not exist on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [bkaradzic/bx#295]
In https://github.com/bkaradzic/bx/blob/master/src/thread.cpp#L27 `pthread_np.h` is included for all BSDs.
NetBSD does not provide that header.
I stumbled over this in the mame project, just removing the header include on NetBSD let the build finish there, i.e.:
```
--- 3rdparty/bx/src/thread.cpp.orig     2023-02-21 17:59:53.000000000 +0000
+++ 3rdparty/bx/src/thread.cpp
@@ -25,7 +25,9 @@
        || BX_PLATFORM_NX
 #      include <pthread.h>
 #      if BX_PLATFORM_BSD
+#ifndef __NetBSD__
 #              include <pthread_np.h>
+#endif
 #      endif // BX_PLATFORM_BSD
 #      if BX_PLATFORM_LINUX && (BX_CRT_GLIBC < 21200)
 #              include <sys/prctl.h>
```
I don't know how you want to fix this since you avoid __NetBSD__ and similar defines in the code, so this patch is just to document that removing the include fixes the build on NetBSD.

**Comment by bkaradzic** [comment]
Modify your own fork, I'm not interested into supporting all those *BSD variants. BSD is such PITA, low number of users, but such opinionated about where headers are, or how to name headers, etc. Not worth the effort.
