### ISSUE TITLE
bx::normalize return bad result when simd is enable on macOS(M1)/iOS platform

### ISSUE THREAD

**Issue by junjie020** [bkaradzic/bx#298]
I have this code:
``` C++
// simd is enable
bx::Vec3 nv = bx::normalize(bx::Vec3(0.f, 1.f, 0.f));
```

On window platform, it will return: nv = (0.f, 1.f, 0.f), as we expected.

On macOS/iOS(ARM architecture), it will return: nv = (0.f, 1.00000572f, 0.f), the y coordinate is slightly larger than 1.

I dig into the code, I found that, **simd_sqrt** with value 1, will return a value less than 1.

It will bring some bad result, like:

``` C++
const bx::Vec3 dir = texelUvToDir(side, uu, vv);

float srcU, srcV;
bx::toLatLong(&srcU, &srcV, dir);
```

> here, _dir_ should return value (0.f, 1.f, 0.f), but we get (0.f, 1.00000572f, 0.f), it cause **bx::toLatLong** return NaN in _srcV_

this code is from:
https://github.com/bkaradzic/bimg/blob/master/src/image_cubemap_filter.cpp#L242

**Comment by cloudwu** [comment]
https://github.com/bkaradzic/bx/blob/master/include/bx/inline/math.inl#L665

I think use `rsqrt` would be better

```cpp
  const float invLen = rsqrt(dot(_a, _a));
```

Because `sqrt` is implemented with `rsqrt` https://github.com/bkaradzic/bx/blob/master/include/bx/inline/simd_ni.inl#L200-L211

On this issue, I suggest to clamp (_dir.y ,-1, 1) in toLatLong
```cpp
inline void toLatLong(float* _outU, float* _outV, const Vec3 _dir)
{
	const float phi   = atan2(_dir.x, _dir.z);
	const float theta = acos(clamp(_dir.y, -1, 1));

	*_outU = (kPi + phi)/kPi2;
	*_outV = theta*kInvPi;
}
```

**Comment by bkaradzic** [comment]
Grab latest...
