### ISSUE TITLE
I'm confused about BX_NO_VTABLE, bx::AllocatorI, and UBSan reports.

### ISSUE THREAD

**Issue by mcourteaux** [bkaradzic/bx#320]
**How I got here:** I was running SilverNode under UBSan, and I'm getting constantly reports involving `bx::AllocatorI`, such as:

```
/home/martijn/zec/3rd/bx/include/bx/inline/allocator.inl:42:22: runtime error: member call on address 0x60800001a2a0 which does not point to an object of type 'AllocatorI'
```

and

```
/home/martijn/zec/3rd/bx/include/bx/inline/allocator.inl:47:29: runtime error: member call on address 0x60800001a2a0 which does not point to an object of type 'AllocatorI'
0x60800001a2a0: note: object has invalid vptr
 00 00 00 00  b8 80 5c 60 55 55 00 00  be be be be be be be be  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
```

**Analyzing this a bit:** Having a look at the information at runtime, I'm seeing:

```gd
(gdb) f 3
#3  0x000055555f4c5d8f in bx::free (_allocator=0x60800001a2a0, _ptr=0x622000013900, _align=0, _location=...) at /home/martijn/zec/3rd/bx/include/bx/inline/allocator.inl:42
42			_allocator->realloc(_ptr, 0, _align, _location.filePath, _location.line);
(gdb) p *_allocator
$8 = {_vptr.AllocatorI = 0x5555605c80b8 <vtable for bgfx::AllocatorStub+16>}
(gdb) info vtbl _allocator
vtable for 'bx::AllocatorI' @ 0x5555605c80b8 (subobject @ 0x60800001a2a0):
[0]: 0x55555ffbf5d2 <bgfx::AllocatorStub::~AllocatorStub()>
[1]: 0x55555ffbf612 <bgfx::AllocatorStub::~AllocatorStub()>
[2]: 0x55555ffbb108 <bgfx::AllocatorStub::realloc(void*, unsigned long, unsigned long, char const*, unsigned int)>
(gdb) 
```

Suggesting that the vtable is there and looks correct (there are two destructors: [the D0 and D2 variants](https://stackoverflow.com/questions/6613870/gnu-gcc-g-why-does-it-generate-multiple-dtors/6614369#6614369), which you can see when manually examining the vtable:

```
0x5555605c80b8 <_ZTVN4bgfx13AllocatorStubE+16>:	0x55555ffbf5d2 <_ZN4bgfx13AllocatorStubD2Ev>
                                              	0x55555ffbf612 <_ZN4bgfx13AllocatorStubD0Ev>
0x5555605c80c8 <_ZTVN4bgfx13AllocatorStubE+32>:	0x55555ffbb108 <_ZN4bgfx13AllocatorStub7reallocEPvmmPKcj>
```
)

So, at runtime, I don't necessarily see an issue. But what confuses me is that `AllocatorI` is marked with `BX_NO_VTALBE`:

https://github.com/bkaradzic/bx/blob/dc3bf2990e62e8e8764de1f430637aa26e333296/include/bx/allocator.h#L23-L49

I'm not sure what the purpose of this is, and what this macro expands to on my system (looking at the source, I believe it actually expands to nothing, as I'm on either Clang or GCC). But perhaps this is a (historic) mistake to tag it with `BX_NO_VTABLE`, as it clearly has a vtable? Perhaps this causes UBSan to report this? Can you shed some light on this?

Either way, believing that the macro doesn't do anything, do you have any other ideas on why UBSan reports this?

I'm making a Debug build of SilverNode (`-fsanitize=address -fsanitize=undefined -g -std=gnu++20 -fdiagnostics-color=always -Wall`), and linking against `bgfxDebug`, `bxDebug`.

**Comment by bkaradzic** [comment]
`BX_NO_VTABLE` is only used for pure interfaces which should not be instantiated.

It's MSVC specific code size optimization:
https://learn.microsoft.com/en-us/cpp/cpp/novtable?view=msvc-170
