### ISSUE TITLE
How to build this repo?

### ISSUE THREAD

**Issue by tintor** [bkaradzic/bx#336]
Seems like it was written for `premake` before v5, but premake 4.3 and 4.4 binaries for x64 are not available anywhere.
`brew install premake` installs v5

```
13:17 marko@nitro:~/repos/bx$ premake5 --file=scripts/bx.lua
Error: /Users/marko/repos/bx/scripts/bx.lua:40: no workspace in scope
```

I am trying to build bgfx on Intel Mac v13.6.3.

**Comment by bkaradzic** [comment]
In repos with GHA you can always find that info in workflow, or CI results:

https://github.com/bkaradzic/bx/blob/109637aa6f304037de95c3b9b5f02f635757d8d8/.github/workflows/main.yml#L118-L120

**Comment by tintor** [comment]
Thanks. What value do I use for `matrix.config`?

What is the recommended way to build `bx`?

**Comment by bkaradzic** [comment]
> What is the recommended way to build bx?

Generate project files with GENie for build system you're familiar. Use build system you're familiar with...
