### ISSUE TITLE
why needs a `wait` here?

### ISSUE THREAD

**Issue by fatfatson** [bkaradzic/bx#337]
https://github.com/bkaradzic/bx/blob/7eace058a2b852055719a61fd24eee66baf436dc/src/thread.cpp#L201

when use bx::Thread in main thread in ios, it will produce a warning:

> Thread Performance Checker: Thread running at User-interactive quality-of-service class waiting on a lower QoS thread running at Default quality-of-service class. Investigate ways to avoid priority inversions
PID: 33841, TID: 37496357

so is it necessary ? should it be removed?

**Comment by bkaradzic** [comment]
You can't just run tool, report issues and offload to someone else to analyze for you... Try to understand what tool is saying, then investigate code, and then if you find it's false positive, figure out how to annotate it, or if it's real bug show that you understand what is it.

**Comment by fatfatson** [comment]
I have read the code and found it's waiting nothing usefull, just wait for the target thread to run into the user function.
so i don't understand why it's need here.

and if it's not reported by the tool, i may not care about it. but it did, so i really would like to know why it is， sincerely ask for advice.
