### ISSUE TITLE
platform.h suggest supported gcc version is 8.4. `__builtin_bit_cast` used by bx.inl wasn't defined until version 11

### ISSUE THREAD

**Issue by imaginaryPineapple** [bkaradzic/bx#338]
I think the project is targetting minimum C++17 and GCC 8.4
https://github.com/bkaradzic/bx/blob/3e9604c7434127b9d5b8964cdebfdc7ac4693581/include/bx/platform.h#L469

`__builtin_bit_cast` didn't get implemented in GCC until version 11, (April 27, 2021).

`bx.inl` uses built-in
https://github.com/bkaradzic/bx/blob/3e9604c7434127b9d5b8964cdebfdc7ac4693581/include/bx/inline/bx.inl#L171
resulting in `error: '__builtin_bit_cast' was not declared in this scope` when building with GCC 9, 10 (tested)

GNU suggests using `std::bit_cast` (introduced in C++20) instead of the built-in.
[GNU GCC Documentation](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005fbit_005fcast)
```
The built-in is intended to be used by implementations of the std::bit_cast C++ template function. Programs should make use of the latter function rather than invoking the built-in directly. 
```

**Comment by bkaradzic** [comment]
Fixed. Thanks!
