### ISSUE TITLE
mtxScale and mtxTranslate are reseting

### ISSUE THREAD

**Issue by MyZeD** [bkaradzic/bx#59]
Hay bkaradzic,

first of all, you've done a great work, but I've encountered an error:
If i set my Scale with mtxScale and after that the Translate with mtxTranslate, so my Scale is gone, if i change the order, then it cleans me my Translate in my mtxMesh.

**Comment by dariomanesku** [comment]
What you're looking for is probably:
float scale[16];
bx::mtxScale(scale, sx, sy, sz);
float trans[16];
bx::mtxTranslate(trans, tx, ty, tz);
float mtxMesh[16];
bx::mtxMul(mtxMesh, scale, trans);

**Comment by bkaradzic** [comment]
Yeah it's intended to be this way. It doesn't concatenate matrices it just sets matrix to desired operation. You might want to use `bx::mtxSRT` to set scale, rotation, and translation at once: https://github.com/bkaradzic/bx/blob/master/include/bx/fpumath.h#L601
