### ISSUE TITLE
string.h: Compile error on msvc2015 

### ISSUE THREAD

**Issue by septag** [bkaradzic/bx#64]
I get compile error when including ```strings.h``` the alloca.h does not exist. I guess adding msvc protector macro around it fixes it :

```
#ifndef BX_COMPILER_MSVC
#   include <alloca.h>
#endif
```

**Comment by bkaradzic** [comment]
You have your own build system?

You forgot to add compat into your include path:
https://github.com/bkaradzic/bx/tree/master/include/compat/msvc

**Comment by septag** [comment]
Yes i was using my own. sorry for that. thx
