### ISSUE TITLE
Visual Studio 2012 and earlier don't have alloca.h

### ISSUE THREAD

**Issue by leetNightshade** [bkaradzic/bx#65]
To get VS2012 to compile I had to add this to bx/string.h
```#ifdef _WIN32
#include <malloc.h>
#define alloca _alloca
#elif
#include <alloca.h>
#endif
```
Please see [here](https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx).

**Comment by bkaradzic** [comment]
Yes, I know, it's here:
https://github.com/bkaradzic/bx/tree/master/include/compat/msvc

Also build system adds it to include dires:
https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L372

If you're changing build system, you should make sure it has the same settings as build system provided.

**Comment by leetNightshade** [comment]
Sorry about that, thanks. I didn't have VS2013 installed yet, so was trying to setup bgfx to use my premake4 setup for VS2012 testing.

**Comment by bkaradzic** [comment]
You can use `genie vs2012` to generate vs2012 project files.

**Comment by bkaradzic** [comment]
More GENie info (it's fork of Premake4.4b5): https://github.com/bkaradzic/genie#what-is-it

**Comment by leetNightshade** [comment]
Cheers! I was aware of Premake on hiatus, would have been nice to discover this sooner.
