### ISSUE TITLE
Suggestion for prefix for debugOutput()

### ISSUE THREAD

**Issue by RichardGale** [bkaradzic/bx#66]
Android, among other platforms, have really chatty output which makes it difficult to locate debugOutput from bx.

Suggest adding BX_CONFIG_DEBUG_TAG to add a custom prefix, e.g. Android this would be:

__android_log_write(ANDROID_LOG_DEBUG, BX_CONFIG_DEBUG_TAG, _out);

Other platforms it could be a simple string prefix.

**Comment by RichardGale** [comment]
https://github.com/bkaradzic/bx/pull/71 adds BX_CONFIG_DEBUG_TAG that allows custom tags, e.g. use the same tag as your app to filter and display logging with your app.

**Comment by RichardGale** [comment]
I had trouble without the BX_STRINGIZE as the ndk-build pipeline didn't honor the quotes (clang 3.5 compiler).

With latest and 2x double quotes:

LOCAL_CPPFLAGS +=  -std=c++11 -DBX_ANDROID_LOG_TAG=""Slots""  -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DBGFX_CONFIG_MULTITHREADED=0 -DBGFX_CONFIG_DEBUG=1

<command line>:#define BX_ANDROID_LOG_TAG Slots8
:28                           ^:
 note#define BX_ANDROID_LOG_TAG Slots: 
expanded                           ^ 
from here
#define BX_ANDROID_LOG_TAG Slots

and 1x double quotes:

LOCAL_CPPFLAGS +=  -std=c++11 -DBX_ANDROID_LOG_TAG="Slots"  -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DBGFX_CONFIG_MULTITHREADED=0 -DBGFX_CONFIG_DEBUG=1

<command line>:8:28: note: expanded from here
#define BX_ANDROID_LOG_TAG Slots

**Comment by bkaradzic** [comment]
What about escaping them? `\"Slots\"`

**Comment by RichardGale** [comment]
For anyone else using cmake as build use a lot of escaping, e.g. 

add_definitions(-DBX_ANDROID_LOG_TAG="\\\\\"MYTAG\\\\\"")
